### ISSUE TITLE
MP: Highlight Tabs with "message count"

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1438] opened 2019-02-11 10:23 UTC
If new information appear they are highlighted on the left bar with a "message count" e.g. on "sell". If open the "sell" item I do not see immediately that this new message origin is the "orders" tab for example.

This is true to all tabs.

# More information

- Operating system and version: all
- Client version: 2.0.0 alpha

**Comment by HenkSwardt** [comment] 2019-02-11 11:57
Hello @DrDBanner 

Thanks for logging the issue. This is a duplicate of a previous request and something we would like to add as a future enhancement

https://github.com/particl/particl-desktop/issues/1412

I will close this as a duplicate

**Closed as completed** 2019-02-11 12:11 UTC
