### ISSUE TITLE
V3 - Publish to shows empty markets list

### ISSUE THREAD

**Issue by pelssersconsultancy** [particl/particl-desktop#1737] opened 2020-12-27 21:28 UTC
**Describe the bug**
When creating a new listing in the final step the publish to show empty dropdown.

**To Reproduce**
1. Go to 'Market'
2. Click on Sell
3. Click on Inventory and Products tab
4. Fill in some product details (not that relevant) and shipping details but skip step publish right away.
5. Click on Wallet (mimicing user who wants to copy wallet address to get some test parts) and make sure you have enough test parts to sell the particular item
6. Click back on Market
7. Click on 'Sell'
8. Click on Inventory and Products tab
9. Click on list item you created in previous steps
10. Click on edit
11. Scroll down to publish settings and expand publish right away
12. Click on dropdown 'Publish to'
13. You see empty dropdown

**Expected behavior**
I expect to see the particl market in the publish to dropdown when creating new listing.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. OSX BigSur 11.0.1 ]
 - Particl Desktop: [e.g. v3.0.0-RC-test002]
 - Particl Core: [e.g. v0.19.1.1]
 
**Additional context**
I first created a listing but had no testcoins so I navigated back to wallet, copied wallet address and tanked some test parts with faucet.  Next I tried to publish the listing but the publish to showed empty dropdown.

**Comment by zaSmilingIdiot** [comment] 2021-01-05 12:31
I'm not able to reproduce this following the provided steps.
I can get a psuedo occurence of the issue int he case that the listing details take some time to load while attempting step 11. In other words, after performing step 10, if the loading of the listing details takes a couple of seconds to display/render, then the market dropdown is blank when performing step 11 - 13. However, as soon as the template details have loaded/rendered, then the market list is updated correctly as well, and the dropdown contains the correct list of markets.

Is this still an issue? And if so, is it possible to still reliably reproduce it following the previously provided steps?

**Comment by zaSmilingIdiot** [comment] 2021-05-06 09:29
Closing this for now, due to it not currently being reproducible across multiple tested instances.

**Closed as completed by zaSmilingIdiot** 2021-05-06 09:29 UTC
Labels: type: Bug, Resolve: Cannot reproduce
