### ISSUE TITLE
Coin conversion "public to anon" will then reset the latter radio button into "blind" state

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1634] opened 2019-08-03 13:17 UTC
Converting funds will reset radiobutton from anon going to blind, i would expect anon to maintain its selection

- Operating system and version: Latest testnet before mainnet
- Client version: win10x64

**Comment by zaSmilingIdiot** [comment] 2019-08-05 07:29
This was by design: reset the radio button controls to their default state. We can look at maintaining the selection as an update to the current functionality, but this will likely occur in a future release if its deemed appropriate.

**Comment by PARTimprovert** [comment] 2019-08-05 09:42
i understand its kind of minor, this is textbook usability theory however

**Comment by zaSmilingIdiot** [comment] 2019-08-05 11:04
Yes, but consider that context matters though. Theory remains theory, and needs to be adapted to the situation it applies to when implemented.

By way of explanation... User interaction flows vertically currently: make selection -> input value -> process action. With the idea that returning to an earlier step possibly invalidates or changes the selections made in a later step in a sequence, the later step selections and inputs possibly need to be reset. In this way, we're changing a later step to keep the flow consistent, but also to ensure that invalid or erroneous inputs (and erroneous here can refer to the value input not being correct for the new, previous "step" selection) are removed.

Considering for example that scenario where after the radio selection is changed, the user doesn't want to transfer the amount previously indicated: now they need to erase the input value. Shortly after that change, we'll be asked why the input amount value is not cleared, because you know, its textbook UX stuff ;p

I'm being facetious, but the point is that we're currently following a particular flow that has been the same throughout the v1 wallets as well. And its not like we're closing this issue: we'll leave it open so that we can address it in a future change. If this is a significant annoyance for people, then sure, we can bump up the priority on it.

**Comment by zaSmilingIdiot** [comment] 2020-10-14 20:26
Added in v3.0 - the radio states will retain their current 'selection' after actioning the conversion.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:34
Closing as it has been resolved in v3.0.0

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:34 UTC
