### ISSUE TITLE
Wrong displayed listing fee

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1785] opened 2021-07-16 22:46 UTC
**Describe the bug**
The displayed listing fee is incorrect when paying either from Anon or Public balances

**To Reproduce**
1. Publish a listing on some market. Note the calculated listing fees value  
2. Open in the blockchain explorer the block with the published listing related txs
3. Compare the calculated value with the real one (what you payed)

**Expected behavior**
The calculated value should be equal to what you actually pay 

**Screenshots**
Available upon request.

**Versions (please complete the following information):**
 - Particl Desktop: [v3.0 RC004 testnet]
 - Particl Core: [e.g. v0.19.2.12]

**Comment by zaSmilingIdiot** [comment] 2021-07-20 08:51
Looking into this.

**Comment by zaSmilingIdiot** [comment] 2021-07-20 12:45
Did the listing by any chance have images with it?

The only way I seem to be able to reproduce this is when the product item has one or more images. In such cases, it seems the image fees are not being included in the item content message fee. This can be seen by viewing the transaction history in the wallet. For example, posting an item with 2 images generates 3 transactions: one for the listing message content and the other 2 for each of the images. The transaction fee for the message content is exactly the estimated fee displayed. However, due to the addition of the image message fees, the total fee is actually more, and its this total fee which is displayed in the block explorer.

Will look at including the image fees in the estimate as well.

**Comment by bacoinin** [comment] 2021-07-20 13:02
Yes that happens when the listings have images.

**Comment by zaSmilingIdiot** [comment] 2021-07-20 16:33
Has been fixed.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:59
Closing: fixed for mainnet release of v3.0.0

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:59 UTC
Labels: type: Bug, version: testnet
