### ISSUE TITLE
Blind/Anon coins missing after passphrase restore

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1448] opened 2019-02-12 18:22 UTC
Testnet - latest build - win10 x64

A few days ago I transferred 20 PART to Blind and 10 PART to Anon. I left them like that for a day or so, then transferred them back to Public. This appeared to work fine, all coins were accounted for in my Public total.

Today, a few days later, I deleted all local data and then restored my testnet wallet using the many-word phrase. It loaded up but with 30 coins missing from the Public balance. In my history, it shows a Sent for ~10 and another Sent for ~20 at about the time I did the restore (I did not do any Sends today with this wallet).

So it appears that the Blind and Anon transfers back to my Public are not getting properly picked up and displayed as part of my total. 

![image](https://user-images.githubusercontent.com/38863166/52658447-ab0f0e80-2ec0-11e9-9846-2890213a7733.png)

**Comment by rynomster** [comment] 2019-02-12 18:24
Hi @CryptoBeans

Did you use a private address at all?
If so, generate a few private Addresses, then run scanwallet in the debug console

**Comment by CryptoBeans** [comment] 2019-02-12 18:34
@rynomster It looks like that fixed the issue. I created 3 private addresses then ran rescanblockchain and now I see the correct 165 Public balance. (scanwallet did not appear to be a command)

Does this mean that the restore process should automatically create some private addresses before doing the scan so that users don't have to do this fix manually?

**Comment by kewde** [comment] 2019-02-12 19:47
There's no HD lookahead yet - this is somewhat expected behavior at this point, but we'll look into fixing it.
Closing this, since it's solved and it's more a `particl-core` issue..

**Closed as completed by kewde** 2019-02-12 19:47 UTC
