### ISSUE TITLE
Shipping profiles not properly stored / updated

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1644] opened 2019-08-03 22:01 UTC
So far the only way to update your shipping profile is to bid for an buy order. 
If I do not finish the bidding (maybe also due to missing funds) the changes in the shipping profile is not beeing stored. 

You are forced to make an order to configure your shipping profile but you also should be able to make changes independently of making any purchase.

1. Go to your cart
2. Go to shipping details
3. Make changes to an shipping profile and change the profile name
4. Continue the buying process to Confirmation but do not finish it all the way through

Win10 64bit
alpha2-testnet

**Comment by btmr** [comment] 2019-08-04 08:34
As far as I'm informed, this behavior is by design at the moment.

I agree that it would be more convenient to be able to edit/save the profile independent from making a purchase.

**Comment by zaSmilingIdiot** [comment] 2019-08-05 07:19
Yep. As @btmr states, this is by design at the moment.

We'll look at updating this in the future, possibly having a solution to manage shipping profiles. But its not an immediate priority.

**Comment by zaSmilingIdiot** [comment] 2020-10-14 19:10
Resolved in v3.0 : the ability to modify saved shipping profiles has been added so as to allow for creation/modification/deletion of shipping profiles outside of the cart.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:34
Closing due to being resolved in v3.0.0

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:34 UTC
