### ISSUE TITLE
Marketplace stuck in loop (and freeze) when doing a purchase

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1297] opened 2018-12-04 21:41 UTC
Hello guys,

This bug will be hard to explain, so i'm really sorry for that. (3 try from sratch with full clean Appdata with the same result)

When i do the standard process to buy something on the marketplace, it does nothing in appearance.

<img width="860" alt="place order" src="https://user-images.githubusercontent.com/44212051/49474239-7d4c8000-f814-11e8-9bd9-882cb4db3421.PNG">

When i click on "Yes, place order" it does nothing ... it comes back to "Confirm & place order screen" i can't see any "bidding" in order. 

but i see a balance transfer in recent transaction ... so i suppose my bidding worked partially. Impossible to see anything in "order" to verify my cart and my current bid.

Then computer becomes hot, ventilation high and then nothings answers anymore (listing doesnt show, proposal doesn't show anymore ect)

I'm forced to close Desktop because it's complicated 5min after every bidding test.

Here is my marketplace.log ;

[marketplace.log](https://github.com/particl/particl-desktop/files/2646228/marketplace.log)

# More information
Operating system and version: win64
Client 1.2.2-20181128-alpha-RC1
Market 0.0.49

**Comment by zaSmilingIdiot** [comment] 2018-12-04 21:53
This looks to be a bug that was actually addressed a couple of hours ago (a
fix has been submitted already).

See: https://github.com/particl/particl-market/pull/338

The problem is in trying to process a large number of small value utxos to
find a combination that sums to roughly the value of the required
transaction amount. As noted in the pull request, 34 such utxos generates
over 17 billion possible combinations. Which when looping over all possible
combinations causes the machine to become unresponsive. The patch places a
reasonable upper bound on the size of the utxo array to be considered for
such processing.

**Comment by zaSmilingIdiot** [comment] 2018-12-05 10:06
Here is a temporary workaround for this specific issue at the moment. It requires editing a file, which if edited incorrectly will break the application. Please be really careful when making these changes. This helps to solve this specific issue so further testing can be done (if you do not wish to wait until the next test build is released).

Pre-requisite: make certain that the desktop application is closed.

1. Find the 'BidActionService.js file in following directory: 
    `../resources/app.asar.unpacked/node_modules/particl-marketplace/dist/api/services/BidActionService.js`
2. Make a backup of this file somewhere.
3. Edit this file, performing the following actions:
    - remove lines 208 - 224 (both inclusive)
    - for reference: line 208 is the line starting with : `// ... Step 2: Sum utxos to find a summed group`
4. Save the changes and restart the desktop app.

Just remember this is a temporary fix if you need it. If you run into problems and the application or marketplace is broken after your changes, simply copy and replace the edited file with your backed-up copy of the file (the one that was created in step 2 above).

**Comment by michmish** [comment] 2018-12-06 20:59
The modification of the file solved the issue ! Well done and thank you

**Comment by zaSmilingIdiot** [comment] 2019-01-08 11:32
Changes applied in https://github.com/particl/particl-market/pull/338 have been merged, and will be included in future builds.

**Closed as completed by zaSmilingIdiot** 2019-01-08 11:32 UTC
