### ISSUE TITLE
V3 - Shopping Cart showing items present when actually empty

### ISSUE THREAD

**Issue by cleansanchez** [particl/particl-desktop#1739] opened 2020-12-28 09:02 UTC
**Describe the bug**

The shopping cart shows there are items in the cart when there are not.

**To Reproduce**
Not sure how to reproduce this. 

![03](https://user-images.githubusercontent.com/44262926/103202697-0a2a7080-48eb-11eb-96fb-6a850ff4c808.JPG)

**Versions (please complete the following information):**
 - OS: [Windows 10 ]
Particl Desktop: [e.g. v3.0.0-RC-test002]
Particl Core: [e.g. v0.19.1.1]

**Comment by zaSmilingIdiot** [comment] 2021-01-05 10:34
I can't seem to reproduce this particular case, at least not without further information.
Had you previously added items to the cart (ie: were there 2 items in the cart to begin with), and then after some action such as checking out or removing the items, the count of items remained but the items were no longer shown?
Whatever action was taken, please describe what it was and whether there any errors occurred?
Did this occur after immediately after starting the application (as in, yo ustarted particl-desktop, opened the market module and noted that the number of items in the cart showed as 2 but there was nothing in the cart)?
Were there any changes applied manually via the marketplace API (or via the market console window in the application)?

**Comment by zaSmilingIdiot** [comment] 2021-01-05 11:04
I seem to have found a means to reproduce this: caused by the market service deleting expired listings. However, there is no indication to the frontend service that such a deletion has occurred, and thus the GUI still indicates that there is something in the cart.

Needs some coordination and discussion with the particl-market service to determine an adequate solution.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:54
Closing: fixed for mainnet release of v3.0.0

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:54 UTC
Labels: type: Bug, version: testnet
