### ISSUE TITLE
Unflagging a listing i personally flagged before doesn't make the listing become unflagged

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1605] opened 2019-07-12 09:06 UTC
Items appear to remain flagged on market listing page even after unflagging it. "I have changed my mind section" on the item itself does show that my flag has indeed been removed (as i'm now able to re-flag). Whether its truly un-flagged or not is unclear to me at this point.

Win 10 x64
latest alpha blind 2.0.0

**Comment by HenkSwardt** [comment] 2019-07-12 09:20
Good day, 

Flagging the item and actually casting your vote are two separate steps. Flagging it just means you feel it is not safe and would like to get consensus on it. Once flagged it will remain flagged. For convenience we took the step to (1) remove it from your view and (2) also cast your vote as you indicated you dont like it. Changing your mind after the fact will just remove your weight from saying it needs to be removed, and we will then place this item back on your view.

To confirm, the item will not be un-flagged

**Comment by PARTimprovert** [comment] 2019-07-12 09:28
I understand thanks for the explanation, but wouldn't it make sense to unflag the listing if it's just your weight and nobody else voted for removal yet? I'd imagine this to be tricky technically..

**Comment by zaSmilingIdiot** [comment] 2019-07-12 10:06
The problem is that there is no means of determining that nobody has voted on it yet. Once the flag proposal has been cast, its effectively a message that traverses the network to other nodes. In between, somebody might have received your flagged proposal message, and then voted on it (sending their vote messages to the network). But your node has not yet received those vote messages when you decide to change your mind: so say a reverse flag message is issued to the network.
Now your node receives the vote messages... what should then happen on your node? What should happen on other nodes that receive and process the various messages in different orders?

Because this is a distributed messaging network essentially, you're aiming at what effectively is eventual consistency. Which means that the state of the MP on a single node at any given time is not necessarily the state of everybody's MP at that same time.

**Comment by zaSmilingIdiot** [comment] 2019-07-12 10:08
The issue is technically "by design", and hence not an issue. I'm closing this now, but the discussion can readily be continued if further clarification is needed.

**Closed as completed by zaSmilingIdiot** 2019-07-12 10:08 UTC
