### ISSUE TITLE
Anon address fails to be generated by default, needs to be generated manually before fund conversion can be established + probable cause

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1635] opened 2019-08-03 13:26 UTC
Couldn't find this logged yet even it has been discussed on discord. I just had the same error.
When i try to convert coins from public to anon, the client gives me an error saying address can't be found. I need to then manually generate an anon address by going to the anon receive tab in order for fund conversion to work.

**I suspect this has to do with an initial failure to initiate the market wallet when it's being created (see my logged issue: https://github.com/particl/particl-desktop/issues/1622 ). My regular wallet didn't gave this behavior, no error message appeared when trying to convert funds here, just my market wallet)**

- Operating system and version: win10x64
- Client version: latest testnet before mainnet

**Comment by zaSmilingIdiot** [comment] 2019-08-05 10:11
Yep, as you determined, the issue is a result of #1622

I'm closing this as a consequence of the events occurring in #1622
When that is resolved, this will be as well.

**Closed as completed by zaSmilingIdiot** 2019-08-05 10:11 UTC
