### ISSUE TITLE
windows warning: unknown method flash notification on wallet creation

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#686] opened 2018-01-16 21:01 UTC
when creating a wallet on the windows packaged version, a flash notification appears with the text `unknown method`. Wallet ccreation is not impacted otherwise.

**Comment by anandsinghparihar** [comment] 2018-01-17 15:19
@pciavald I can't see wallet is created, after complete all wallet creation step I see a blank modal.

**Comment by EagleEye25** [comment] 2018-01-23 08:13
i cant get past enter recovery phase, but till this point i dont get the `unknown method` issue, all the other flash notifications show what it should, also looked in the code on create wallet, and all the messages are hard coded, and dont rely on any variables or methods for information. @pciavald @HenkSwardt

**Comment by HenkSwardt** [comment] 2018-01-25 12:16
@EagleEye25 will try this again using the 1.1.0 release branch as changes made to it after RC3 should allow him to create the wallet fully now.

**Comment by HenkSwardt** [comment] 2018-01-29 08:35
@kewde  and @pciavald  we are not able to reproduce this issue at all, Please confirm if this can be closed for now?

**Comment by kewde** [comment] 2018-01-29 10:02
Closing it for now.

**Closed by kewde** 2018-01-29 10:02 UTC
Labels: PRG, enhancement, needs-testing
