### ISSUE TITLE
Bulk upload breaks some characters...

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1680] opened 2019-11-23 08:30 UTC
Using the bulk upload feature breaks some characters. E.g.

 - Long Hyphen
 - Registered trade mark symbol
 - Apostrophe as in dad's
 - Any charter with an accent such as acute e - É
 - There are many more...

Any of these character is replaced with a question mark in a diamond. Manual upload does not seem to have this problem when I copy paste.
 
I am working in a recent version of Microsoft Excel to edit the CSV version 9012 32 Bit. It could also be this which is introducing the character issues. I can test as far as manual copying and pasting the listing from the .csv in excel into Particl Desktop and saving the listing, but this does not reproduce the error so it may be the import function that is the issue. 

I am working in windows 10 64 bit.

**Comment by githubrsys** [comment] 2019-12-01 15:24
I assume you did not save your excel file as UTF-8 compliant. May be an option to identify that by the importer somehow.

**Comment by zaSmilingIdiot** [comment] 2019-12-02 12:52
This appears that it might be related to the way that MS Excel is saving (and possibly opening) CSV files on your machine. More specifically, as @githubrsys mentioned, this appears to be due to the character encoding used by MS Excel on your machine.

By default UTF-8 is supported, and as per the screenshot below, special characters are definitely supported. Confirmed the import on Windows as well, although using Notepad to edit/save the CSV file (which notably defaulted to UTF-8 character encoding in the test case). 

![example](https://user-images.githubusercontent.com/30551211/69960366-f3f88800-1511-11ea-8264-10f7330bbc8f.png)


Using MS Excel to open the same CSV file in this test case rendered the special characters differently, and attempting to update the characters correctly, and then saving the file as CSV, rendered a different set of characters when viewing the newly saved CSV file in Notepad (using a UTF-8 encoding). , Clearly different character encoding was being utilized.

Generally speaking, I'd say MS Excel support for CSV files (even more so UTF-8 encoding) is not exactly great. Or even good. We can possibly add in some text somewhere in the import screen in the application to indicate that files should be UTF-8 encoded, but I don't think this really solves anything; users aren't exactly aware of what character encoding they are using. And it seems unnecessarily complex in Excel to set this when saving files.

**Comment by githubrsys** [comment] 2019-12-09 11:09
Zendesk is quite strict with it as there is no ideal technical solution. Best to do is to educate users; In this case "power-users"

https://support.zendesk.com/hc/en-us/articles/360022361693-Resolving-This-file-is-not-encoded-as-UTF-8-errors-when-uploading-User-CSV-files

**Comment by zaSmilingIdiot** [comment] 2021-09-16 10:37
The csv import mechanics have been updated somewhat in the v3.0 PD client. But as previously mentioned, there are always potential issues when different encodings are used. For this reason, in v3.0, there is an attempt to detect the file's encoding when parsing it, with a default fallback to utf8. In theory this should offer better support for csv files exported by MS Excel for example.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:37
Better support for csv file encoding has been provided in v3.0.0
If there are any further issues, this issue can always be re-opened or a new issue can always be created.

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:37 UTC
Labels: type: Feature Request
