### ISSUE TITLE
Desktop Stuck after creating a new wallet 

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1197] opened 2018-10-16 21:18 UTC
# Describe bug/issue
 Right after successfully passed the process of creation of a new wallet the Desktop freeze and stays stuck like that. Forced to close Desktop and create a new wallet

<img width="1076" alt="fail_wallet_creation" src="https://user-images.githubusercontent.com/44212051/47044550-c8410400-d190-11e8-846f-590bf7f98a09.PNG">

# How to reproduce

1. Do all the step for a new wallet (create wallet, name it, Continue, recovery phrase OK) with syncing not over
2. click on the last OK to launch the creation
3. Desktop stuck

# More information

- Operating system and version: Windows 10
- Client version: 1.2.2-alpha-RC1

**Comment by michmish** [comment] 2018-10-16 21:19
bug reproduced 2 times

**Comment by zaSmilingIdiot** [comment] 2018-10-17 07:07
From the screen capture provided, it appears as though there are a number of issues:
- the wallet appears to have not been found,
- there is a modal display with no content,
- there is a time sync issue

The reported issue may be related to one or more of the above, and may have a common root cause, or could have been a cascade of event errors.

This needs to be investigated further.

**Comment by HenkSwardt** [comment] 2018-10-17 07:26
Hello @michmish 

Can I ask that you please try to reproduce it one more time and provide us with the log files?

Thank you

**Comment by kewde** [comment] 2018-10-17 14:16
Seems like an old RC. Is it reproducible on 1.3?

**Comment by michmish** [comment] 2018-10-17 20:07
Hi,
can't reproduce it anymore (i don't have the sync issue anymore on my computer ... hour has been updated on my computer after the test)
I have selected the log file corresponding to my test yesterday with the bug
[log_bug_desktop.txt](https://github.com/particl/particl-desktop/files/2489079/log_bug_desktop.txt)

**Comment by zaSmilingIdiot** [comment] 2018-11-09 15:43
Looks like the daemon was not starting correctly - the missing cookie file as indicated in the log suggests this.

I'm closing this as there is no further troubleshooting that can be done in this particular case.

**Closed as completed by zaSmilingIdiot** 2018-11-09 15:43 UTC
