### ISSUE TITLE
Image Sizes Should be Standardized

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1151] opened 2018-09-18 00:30 UTC
As seen in the following screenshot: 
<img width="1440" alt="screen shot 2018-09-17 at 8 27 18 pm" src="https://user-images.githubusercontent.com/27031337/45657404-40e07200-bab8-11e8-8d35-3a0e93e55322.png">

Listing images are not the same size. They are all displayed in different proportions and the "squares" are not the same size (which I assume is because of the native dimensions of the image). 

This would look much better if all listing images were displayed with exactly the same proportions and all be perfectly aligned.

**Comment by HenkSwardt** [comment] 2018-09-18 05:27
Good day @cryptoguard 

Thank you for logging this. We have this on the agenda. Please see https://github.com/particl/particl-desktop/issues/974.

Closing this issue as a duplicate

**Comment by zaSmilingIdiot** [comment] 2018-09-18 05:45
Duplicate of #974

**Closed by zaSmilingIdiot** 2018-09-18 05:45 UTC
