### ISSUE TITLE
When entering shipping profile name checkbox should be automatically checked

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1688] opened 2019-12-10 17:01 UTC
When you fill out the "Enter Shipping Address" form and fill out the "Shipping profile name" field on the bottom the intention of the user is to store this data. Due to convenience the "save shipping profile" checkbox should get checked automatically. That way we prevent accidentally filling out the form and forcing the user to do it again in case he misses to check the box, which is frustrating to some not so patient persons. Those who are do appreciate this feature.

 ![bar](https://i.imgur.com/JATooPU.png)

**Comment by zaSmilingIdiot** [comment] 2021-09-16 11:23
Its not immediately obvious though that this is the intention of the user. For some users, this may be the case, but then for other users they may be entering in a single use shipping address and don't need to store the address. The problem is that as soon as assumptions start being made, the system is attempting to invoke implicit knowledge about what the user requires or needs. Which, while helpful for some number of users, these assumption may be incorrect and thus annoying for some other group of users. Additionally, if we managed to make the correct assumption for all users, then the question is should the option exist at all? Since the system should technically be able to automate that choice away so that its "easier" for the user to use the system (for some definition of usage and ease). But this is perhaps starting to digress from the point.

v3.0 of PD caters to providing an explicit location/area for creating and updating shipping addresses (outside of the cart). Additionally, the ability to create and/or update an address from the cart/checkout page is also possible (as is the ability to select a previously saved address as well). 
If the buyer wishes to save the entered shipping address, either creating a new one or modifying an existing one, then a checkbox is provided for that purpose. However, this checkbox is **not** automatically enabled: again, the user can make such modifications in the place explicitly catering for this purpose, and its really not significant effort to check the box while modifications are being made to the address already (if the checkbox is viewed as a confirmation for the save of the address,  then actioning the checkbox requires less effort from the user than the alternative of the user waiting for a confirmation prompt and clicking on a button to confirm that they do in fact, want to save the changes).

I'd apply the above argument to the v2 checkbox as well, but realistically, there wasn't an alternative for saving/modifying shipping addresses, so I can perfectly understand the issue raised. Which is why with the specific are available for creating/modifying the shipping addresses outside of the checkout process itself is useful and helps with regards to shipping address capturing and editing.

**Comment by zaSmilingIdiot** [comment] 2021-09-29 11:43
While not exactly the requested functionality, a means of managing/updating/selecting shipping addresses is available in v3.0.0, as per my previous comment.

Closing this as resolved for now.

**Closed as completed by zaSmilingIdiot** 2021-09-29 11:43 UTC
Labels: type: Feature Request
