### ISSUE TITLE
Anon coins DO NOT restore during wallet recovery

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1621] opened 2019-08-01 17:08 UTC
I had 4 Anon coins, 78 Blind coins, and 9 Public coins in a testnet wallet. I deleted that wallet and all particl folders then re-installed Particl Desktop. I restored the wallet.

Upon restore, I saw the 9 public coins, but 0 for Blind and Anon.

I created a Private/Stealth address and this caused the 78 Blind coins to show up. Still 0 for Anon coins. 

I did a transfer to Anon from Blind to see if it could "find" the 4 coins. 78 Blind Coins transferred to Anon, but the other 4 did not show up even after 12 confirmations.

I restored this wallet again using the 20-words. Now, the 78 and the 4 Anon coins are not showing up.

Update: I saw this happen using the win10 exe version of the alpha2 release. I was able to recreate it a second time. However, another user used the linux-amd64.deb version and reported that the Anon coins restored just fine.

**Comment by CryptoBeans** [comment] 2019-08-02 15:20
I restored this wallet a third time and now what should be ~77 (and another 4) Anon coins is displaying as: 
![image](https://user-images.githubusercontent.com/38863166/62380287-878f5d00-b50e-11e9-94ed-5fc36d0d44d9.png)
The 384 is approximately 77 times 5 so I am guessing it is counting each Anon utxo even though only 1 of them should be valid (I did 5 marketplace buy/sells when this wallet was restored the second time, but this third time in which these values display it has been restored as a wallet named "testnet" and NOT market-enabled). Regardless, the 77 times 5 theory still lacks the original 4 Anon coins that I had which I've not been able to find yet (those 4 coins were the result of escrow releases during the previous testnet release, could that have something to do with it?)

When I try to transfer those 384 Anon coins to Public, I get this error:

![image](https://user-images.githubusercontent.com/38863166/62380436-d0dfac80-b50e-11e9-86e6-491a4ee6ef1b.png)

So that seems to imply there is a display issue with how it is counting the Anon utxo's. 

I then transferred 50 Anon coins to Public and it appears to work, however the values once again displayed oddly (the Public went 9 -> 59 just fine, but the Anon now went 384 -> 309)

![image](https://user-images.githubusercontent.com/38863166/62380615-29af4500-b50f-11e9-8315-a2d22bf7bb51.png)

**Comment by zaSmilingIdiot** [comment] 2019-08-03 09:04
We're busy investigating this. But, here are some comments on the above issues in the meantime:

Firstly, there seems to be an issue that when restoring a wallet to a fully synced and up to date node, then stealth address funds in that wallet are not necessarily restored. The funds however, are not lost. Performing a reindex should re-display any missing blind or anon funds again. In saying that, there has already been some changes in core around anon related fund scanning, but with regards to a slightly different but related topic. I suspect that these changes should resolve the same missing funds on a wallet restore issue that you've encountered, but this is still being tested though on the desktop side of things. However, the changes should resolve your oversupply of anon funds issue.

Just to note that its not a OS specific issue. It may be the case that the restoration of the funds using a Linux OS could likely have occurred because the daemon was still busy syncing at the time of the wallet restore, and the transaction(s) in which anon funds were involved had not yet been scanned.

Then, apart from there being additional funds, it is likely possible that the sending of x PART from anon to public results in a decrease of (x+y) available anon funds: this is to be expected depending on the size of the uxto's used as input into the transaction. So, by way of example: if you transferred 50 PART from anon to public, but had 2 anon utxo's of 60 PART and 10 PART respectively, then the 60 PART utxo would be used as the input to the transaction with 50 PART going to the public address and the 10 PART change being returned. Once there have been sufficient confirmations, then the available spendable anon funds should display correctly.

**Comment by kewde** [comment] 2019-08-03 10:03
Hi,

Please regenerate all the stealth addresses that you've used in the past and then run `rescanblockchain 0`. That will solve your problem.

**Comment by CryptoBeans** [comment] 2019-08-05 12:55
@kewde if you have to regenerate your used stealth addresses then that implies the passphrase alone isn't enough to recover your funds. 

@zaSmilingIdiot I rescanned 2 instances of this wallet, the first is market-enabled and the second isn't. The display values are quite different. I'm not sure if this affects spend-ability but it certainly looks like there is a display issue going on:
![image](https://user-images.githubusercontent.com/38863166/62466151-3b365e00-b756-11e9-9fba-69765f85d99f.png)
![image](https://user-images.githubusercontent.com/38863166/62466181-4ee1c480-b756-11e9-84c9-8ca9d104007c.png)

**Comment by zaSmilingIdiot** [comment] 2019-08-07 11:52
@kewde is 100% correct. He's provided a mean to make the rescan easier (which will be included in the next update), but it is necessary to re-generate the stealth addresses used previously.

Backing up the wallet file should probably be the preferred backup/restore mechanism, with the mnemonic restoration probably being used as a last resort in case of issues. We'll look at incorporating backup/restore mechanisms for the wallet files (similar to the QT application) into the desktop application going forward.

**Comment by kangoala** [comment] 2019-08-07 23:57
When recovering market wallet from seed, the number of coins in my balance also changed on alpha3 testnet. I am not able to send anon coins to public and because I get an error message:

bad-anon-dup-ki (code16)

After creating a stealth address I also got the same error message first, but then the balance changed again to a more reasonable value and since then it's also possible again to convert coins without error message.

- Win10 64 bit:
- testnet-alpha2 and alpha3

I can provide a bunch of screenshots if needed, but I guess it's definitely related to the stealth addresses.

**Comment by cryptoguard** [comment] 2019-08-20 18:06
@CryptoBeans 

We've identified this bug as a minor bug and it qualifies for bounty payment. Please write in this comment section a private address of yours so that we can forward your bounty payment. 

Thanks for participating in the bug bounty and helping us identifying issues! It is really appreciated!

**Comment by zaSmilingIdiot** [comment] 2019-08-21 09:08
Just to note: this is not exactly a bug though. Its expected behaviour insofar as restoration via mnemonic basically indicates that this is more a 'manual' restore in the face of all other information being lost.

This issue does however highlight the need to encourage backup/restore of the wallet file itself in Particl Desktop, and use the mnemonic as the 'last resort' restoration mechanism.

**Comment by zaSmilingIdiot** [comment] 2021-09-16 10:13
Core provides a form of lookahead scanning of stealth addresses as needed.
This issue can for the most part be considered resolved.

**Closed as completed by zaSmilingIdiot** 2021-09-16 10:13 UTC
