### ISSUE TITLE
Items are not beeing added to the cart

### ISSUE THREAD

**Issue by Induvoskos** [particl/particl-desktop#1689] opened 2019-12-12 09:23 UTC
**Describe the bug**
Items are not being added to cart after pressing the "add to cart" button, even though the message "Item has successfully added" pops up.

**To Reproduce**
1. Go to any listing
2. Click on add to cart
3. Go to the cart
4. See that no items have been added 

**Expected behavior**

**Screenshots**
Screenshot 1: "Item has successfully added" message pop up.
![Screenshot from 2019-12-12 10-09-42](https://user-images.githubusercontent.com/51204018/70699327-37e54d00-1cc9-11ea-9635-d328cd38b262.png)
Screenshot 2: Empty cart
![Screenshot from 2019-12-12 10-21-34](https://user-images.githubusercontent.com/51204018/70699387-53505800-1cc9-11ea-813e-6eec969df3e1.png)

**Versions (please complete the following information):**
 - OS:  Linux Ubuntu 18.04
 - Particl Desktop:  v2.3.1

**Additional context**

**Comment by githubrsys** [comment] 2019-12-12 17:26
I can confirm on same MP client version but on mac. But yesterday it worked. No update since then. Mentionable is the missing counter for items beside the basket icon.

While I was searching for a cause, which I could not find, and I clicked through all Market Modules and Wallet Modules the Cart was appearing with 4 items within which I added to the cart some minutes ago. 

Sorry. Can't reproduce.

But if I remember correctly that I had 2 days ago an item in the cart but never finished the purchase. I left the computer. The next day after hibernation the Particl Desktop App was crashed. Today I opened it to see new listings. Then I ran into the same issue as mentioned above.

![issue image](https://i.imgur.com/RKvemmG.png)

**Comment by Induvoskos** [comment] 2019-12-14 20:39
Update: Pressing clear cart even though it was empty worked. Now I can normally add items to the cart

**Comment by HenkSwardt** [comment] 2019-12-17 10:14
Good day, 

Thank you for reporting this, we have logged an issue and will be investigating the issue.

**Comment by zaSmilingIdiot** [comment] 2019-12-24 08:49
Should be fixed in v2.3.2

**Closed as completed by zaSmilingIdiot** 2019-12-24 08:49 UTC
Labels: type: Bug
