### ISSUE TITLE
during Sync - wallet replays before your eyes

### ISSUE THREAD

**Issue by dasource** [particl/particl-desktop#893] opened 2018-03-12 09:48 UTC
1. There is currently *still* no way to know the status of the P2P network aka Is this client in sync or not?

2. Even though I was several weeks out of Sync I received no prompt to notify on load that the wallet was out of sync.

3. Whilst the wallet is getting into sync, the whole Desktop wallet replays infront of your eyes.
So you will see things like "Cold Staking Node" status go from 100% to other % and to other %.
You see the balances consistently change

This along with the lack of 1. and 2. leaves the user is a very confused state.
This needs to be addressed urgently.

**Comment by HenkSwardt** [comment] 2018-03-12 12:00
Hi @dasource 

I had another quick look into the syncing issue explained in this issue. Please let me know if my understanding is incorrect with regards to the issue you logged. Below is a screen sot of a wallet I just started that was  days behind with its sync, a few seconds after launching the notification popped up to inform me that it needs to synch as it is out of date, 

![wallet syncing](https://user-images.githubusercontent.com/28799964/37282502-526ca458-25fd-11e8-80d4-d2f575d2139f.PNG)

If this modal are closed we also have a synch status at the bottom left corner to indicate the percentage synced. When clicking on this you will be able to launch the original sync modal. 

![wallet syncing2](https://user-images.githubusercontent.com/28799964/37282580-a0c632f4-25fd-11e8-9767-8c813a8ec837.PNG)

**Comment by anandsinghparihar** [comment] 2018-03-21 11:25
@HenkSwardt I tried with the latest release and I can't see sync modal, but I created .deb file using current `develope` branch and its work fine for me.

**Comment by zaSmilingIdiot** [comment] 2018-10-08 06:42
I'm closing this as a duplicate of #798 
Further discussions on this should continue in that issue.

**Closed by zaSmilingIdiot** 2018-10-08 06:42 UTC
Labels: duplicate
