### ISSUE TITLE
Desktop 2.0.2 will not exit on Mac OS X

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1659] opened 2019-09-12 20:48 UTC
Desktop 2.0.2 will not exit on Mac OS X. When the close button in the window is pressed the application remains running in the OS seemingly indefinitely. There does not appear to be a quit option either in the app but I think that is intentional as closing the window normal works fine on other systems. Force Quitting via the OS seems to be the only solution. Have tested this on v 2.0.2 of Desktop on Mac OS X versions of El Capitan and Mojave.

**Comment by HenkSwardt** [comment] 2019-09-13 05:05
Thank you for logging this issue. 

Please note this has been resolved and will be available with the next release. 

Marking as a duplicate of https://github.com/particl/particl-desktop/issues/1650

**Comment by zaSmilingIdiot** [comment] 2019-09-13 05:36
Closing as a duplicate of https://github.com/particl/particl-desktop/issues/1650

**Closed as completed by zaSmilingIdiot** 2019-09-13 05:36 UTC
