### ISSUE TITLE
Orders: enable sort/filter

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#1058] opened 2018-06-11 15:03 UTC
### Sorting/filtering

Orders don't have sorting & filtering implemented yet. The code is ready, but we need the functionality.

> _Note:_ the filter is currently hidden via CSS. Remove the [`display: none`](https://github.com/particl/particl-desktop/blob/market/src/app/market/shared/orders/orders.component.scss#L5) from `orders.component.scss`.

### New filter options

![screenshot from 2018-06-11 16-51-06](https://user-images.githubusercontent.com/1965795/41239056-d4ada250-6d97-11e8-90c2-7ce1a3c75308.png)

If possible, can we add these checkboxes below "Search & Sort"? (Crude mock-up above)

- **Hide completed orders** – checked by default?
- **Orders requiring attention** (better wording, anyone?) – this would show only orders that need action from user (for Buyers: Awaiting & Shipping; for Sellers: Bidding & Escrow)
- **Hide old** – hide orders not updated in last 30 (?) days

**Comment by HenkSwardt** [comment] 2018-06-12 08:41
This is a duplicate of https://github.com/particl/particl-desktop/issues/888. Closed as duplicate as this issue has more detail.

- [ ]  Search and sort needs to be able to filter correctly.
- [ ]  Filter by Status should be able to filter correctly.
- [ ]  Clear all filters” button should reset all user selected data.

**Comment by HenkSwardt** [comment] 2018-06-12 09:22
Issue logged on Jira. Thank you

https://particl.atlassian.net/browse/PD-229

**Comment by zaSmilingIdiot** [comment] 2018-10-17 08:36
This has been implemented, and is working as described.

**Closed by zaSmilingIdiot** 2018-10-17 08:36 UTC
Labels: enhancement, market
