### ISSUE TITLE
More details on cancelled orders message box

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1814] opened 2021-09-11 16:08 UTC
Having cancelled a requested order, a message gets displayed whether the seller or buyer canceled the order. (for example "You have rejected this order request and it has beend cancelled" or "Seller rejected the request for this item, order has been cancelled (no money was spent)")

Cancelling from other order states (e.g. Accepted or Escrow), however doesn't give enough details to retrace at a later point why this order has been cancelled and during which order status it has been cancelled by whom. More details at the cancelled order message box would be nice.

**Comment by zaSmilingIdiot** [comment] 2021-09-13 06:37
This is a duplicate of the issue #1743 logged by yourself apparently 😸

**Closed as completed by zaSmilingIdiot** 2021-09-13 06:37 UTC
Labels: Resolve: Duplicate
