### ISSUE TITLE
Error | "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#1409] opened 2019-02-06 14:42 UTC
# Error | "A JavaScript error occurred in the main process"

On a clean install of the new alpha community builds I received a permissions error, JS error.

![image](https://user-images.githubusercontent.com/6236019/52348544-9202eb00-29f2-11e9-874f-77d96bb591e0.png)

# How to reproduce

1. Delete previous testnet builds of marketplace in `/AppData/Roaming`
2. Run `Particl Desktop.exe`

# More information

- Operating system and version: Win 10
- Client version:
![image](https://user-images.githubusercontent.com/6236019/52348865-53b9fb80-29f3-11e9-912e-0e62d34e2248.png)

**Comment by LiteBit** [comment] 2019-02-06 14:46
Clicking "OK" button removes error screen and brings up modal for Updating daemon.

App then does nothing. The screen remains and green progress bar runs with no further indications of continuing. 
![image](https://user-images.githubusercontent.com/6236019/52349071-be6b3700-29f3-11e9-8a87-997726d1d57e.png)

**Comment by zaSmilingIdiot** [comment] 2019-02-06 14:46
Hmmm... looks like the application is being executed out of the zip file directly. You need to extract the files first, and then run the application from the extracted folder.

**Comment by zaSmilingIdiot** [comment] 2019-02-06 14:47
Meh, nevermind, I read that completely incorrectly. Sorry

**Comment by LiteBit** [comment] 2019-02-06 14:54
Closing app by clicking "X" in upper right and then also force closing background app does a proper close of the build. 
![image](https://user-images.githubusercontent.com/6236019/52349663-050d6100-29f5-11e9-8bed-8949df653ad2.png)

Opening `Particl Desktop.exe` again **brings everything up properly**, syncing, peers, daemon download, etc.

**Comment by zaSmilingIdiot** [comment] 2019-02-07 06:53
Thanks LiteBit.

Can you perhaps provide your Windows 10 details? Such as current build and 32/64-bit? This might be useful with regards to a testing environment setup.

We haven't seen this before in testing, hence the reason for the above details

**Comment by HenkSwardt** [comment] 2019-02-07 07:44
This has been logged for investigation. https://particl.atlassian.net/browse/PBD-220

**Comment by zaSmilingIdiot** [comment] 2020-10-14 17:48
Hasn't been reproducible in testing, nor in an additional reported use cases. Closing this for now as its likely not applicable any longer.

**Closed as completed by zaSmilingIdiot** 2020-10-14 17:48 UTC
