### ISSUE TITLE
Missing blind balance and transactions after activating cold staking then restoring wallet using seed

### ISSUE THREAD

**Issue by 88yysu5o78zl** [particl/particl-desktop#950] opened 2018-04-26 17:50 UTC
Bug:
The original wallet held a public and blind balance, cold staking was activated and did not sync fully as PC crashed. Wallet was restored using correct seed to another PC. Initial blockchain sync resulted in the public transactions and balance recovered, however the blind balance and transactions are missing from the recovered wallet.

Windows 7/10 x64 Part Desktop 1.1.0
..

Describe the steps needed to recreate the bug/issue:

1. Create a new wallet and save recovery seed
2. Receive public fund transaction and receive private fund transaction
3. Transfer some public balance to blind balance
4. Activate cold staking and do not sync fully
5. Take original wallet offline and restore wallet on another system using recovery seed
6. Public balance and transactions are shown, private transactions and balance are missing

**Comment by kewde** [comment] 2018-04-27 19:12
Unlock wallet and run
```scanchain 0```

**Comment by 88yysu5o78zl** [comment] 2018-04-27 22:59
Sorry but this didn't work... my blind balance is still 0.00..... do I need to importstealthaddress or another feature to get the wallet to recognize my stealth address and blind balance/transaction?

**Comment by kewde** [comment] 2018-04-28 18:12
Tecnovert spent the whole day testing the recovery from HD seed with regards to blinded transactions and hasn't ran into any issues. 

If you have both wallet.dat files (the original and the newly created one) then we can actually investigate something. Closing this issue for now as it is not reproducible.

**Closed by kewde** 2018-04-28 18:12 UTC

**Comment by kewde** [comment] 2018-04-28 18:34
As suggested by a developer - recreate a few stealth addresses (either through the GUI, or from through the debugconsole: getnewstealthaddress). Recreate about 20 of them (or whatever amount of addresses you suspect might've been created initially) and then run 'rescanblockchain 0'.

**Comment by kewde** [comment] 2018-04-28 18:37
Below is the log, unable to reproduce this bug.
```
./src/qt/particl-qt -testnet -wallet=testrecover1.dat -debug
situate reward bulk boss fly very grunt wife valley height hat oblige arrest music spring fly bonus gloom praise truck arch sand save marine


getnewaddress plainaddr1
pqyuYk1txzb5gXpQP6P8vquoBFhqQHGsHB

getnewstealthaddress sxaddr1
TetcXynmdXRRXAVfReuuAfNRfXsxUMMCChZPFub7pex3Q983NP1ZYtitSeWnr9LBZLRMv63Y8Hev57tRhq4WUHLZtxaRz9VqGqjgkV

other node:
    sendtoaddress pqyuYk1txzb5gXpQP6P8vquoBFhqQHGsHB 1
    17880555b4c427ea0678fd1ccf265d8f4d7e5f4d2c8e6d47f68cdd302023a966


sendparttoblind TetcXynmdXRRXAVfReuuAfNRfXsxUMMCChZPFub7pex3Q983NP1ZYtitSeWnr9LBZLRMv63Y8Hev57tRhq4WUHLZtxaRz9VqGqjgkV 0.5
775036a5219cd9313906726551ebf87e65caad47fe0e9f8787a5099fe09882cc


walletsettings changeaddress {\"coldstakingaddress\":\"pparszMGTpoCdCv3oVf2Bdg8fCRHY4ukP1wMzyq276pt8DnNKPpMJnmTc4cb78RxnsDwyoYP9RVqVejaTLwBth4ysKvG9m8DfnouirRH1bync29a\"}
{
  "changeaddress": {
    "coldstakingaddress": "pparszMGTpoCdCv3oVf2Bdg8fCRHY4ukP1wMzyq276pt8DnNKPpMJnmTc4cb78RxnsDwyoYP9RVqVejaTLwBth4ysKvG9m8DfnouirRH1bync29a",
    "time": 1524939522
  }
}

getwalletinfo
  "walletname": "testrecover1.dat",
  "walletversion": 60000,
  "total_balance": 0.99419000,
  "balance": 0.49419000,
  "blind_balance": 0.50000000,


./src/qt/particl-qt -testnet -wallet=testrecover2.dat -debug
situate reward bulk boss fly very grunt wife valley height hat oblige arrest music spring fly bonus gloom praise truck arch sand save marine

getnewstealthaddress
TetcXynmdXRRXAVfReuuAfNRfXsxUMMCChZPFub7pex3Q983NP1ZYtitSeWnr9LBZLRMv63Y8Hev57tRhq4WUHLZtxaRz9VqGqjgkV

rescanblockchain 0

getwalletinfo
  "walletname": "testrecover2.dat",
  "walletversion": 60000,
  "total_balance": 0.99419000,
  "balance": 0.49419000,
  "blind_balance": 0.50000000,
```

**Comment by 88yysu5o78zl** [comment] 2018-04-30 19:02
Thank you, regenerating stealth address worked!!!
