### ISSUE TITLE
Cold staking not activating

### ISSUE THREAD

**Issue by mfts** [particl/particl-desktop#1026] opened 2018-05-30 13:16 UTC
# Describe bug/issue
I assume that when I have PARTs in my wallet and the wallet is "Unlocked, staking only" that I will be able to add my cold staking node's Public Key. However the icon is just grey and I cannot enable cold staking.

Am I missing something? See video:
![particl](https://user-images.githubusercontent.com/4049052/40722352-5e47699a-641c-11e8-9a74-d6383a9e0ba9.gif)

# More information

- Operating system and version: macOS 10.13.4
- Client version: 1.1.0
- Daemon version: 0.16.0.5

**Comment by kewde** [comment] 2018-05-30 14:57
Dupe of #930

**Closed by kewde** 2018-05-30 14:57 UTC
