### ISSUE TITLE
Crash on startup ( could not connect to daemon)

### ISSUE THREAD

**Issue by fellz** [particl/particl-desktop#756] opened 2018-01-24 12:20 UTC
# Describe bug/issue
Crash and js pop with error
added screen

![screenshot_2](https://user-images.githubusercontent.com/96966/35331902-115025d8-011a-11e8-8188-176b7054df5f.jpg)

# How to reproduce
Just start the app "Particl Wallet"

# More information
- Operating system and version: Windows 10
- Client version: 1.0.0

**Comment by kewde** [comment] 2018-01-24 17:10
@fellz 

Please execute the executable from a command line, that should output more verbosely to the console, that way we can see what's going on, thanks!

@pciavald @dasource Am I mistaken or is this the downloading bug?

**Comment by kewde** [comment] 2018-01-24 19:42
Note to devs:
potentially caused by timeout of RPC, 15 seconds is the default timeout.

**Comment by fellz** [comment] 2018-01-24 20:20
ok here is the log from console

C:\Program Files\Particl Wallet>
[23:16:04.733] [debug] Daemon not running. It will be started bt the daemon manager
Initializing...
Resolving path to client binary ...
Platform: win
Client binary path: C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe
Checking for new client binaries config from: https://raw.githubusercontent.com/particl/partgui/master/modules/clientBinaries/clientBinaries.json
Status: loadConfig - Fetching remote client config
Status: loadConfig - Fetching local config
No "skippedNodeVersion.json" found.
Status: scanning - Scanning for binaries
Initializing Manager...
Resolving platform...
Calculating possible clients...
1 possible clients.
Verifying status of all 1 possible clients...
Verify particld status ...
particld binary name: particld.exe
Exec: "where particld.exe"
Command particld.exe not found in path.
Checking for particld binary in C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked ...
Got optional folder binary for particld: C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe
Running particld sanity check for binary: C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe ...
particld binary path: C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe
Checking for particld sanity check ...
Checking sanity for particld ...
Exec: "C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe -version"
Sanity check output: Particl Core Daemon version v0.15.0.4.0-993ad0c
Copyright (C) 2009-2017 The Particl Core developers
Copyright (C) 2009-2017 The Bitcoin Core developers

Please contribute if you find Particl Core useful. Visit <https://particl.io/>
for further information about the software.
The source code is available from <https://github.com/particl/particl-core>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.

Sanity check passed for C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe
Status: filtering - Filtering available clients
Status: done - undefined
starting daemon C:\Users\Dave\AppData\Roaming\Particl Wallet\particld\unpacked\particld.exe
.....
and it's not closing or anything just hanging ....

**Comment by ThomasPerche** [comment] 2018-01-28 01:02
Same issue for me. Just trying both version (zip and exe) 1.0.0 on win 10 64 bits

**Comment by kewde** [comment] 2018-01-28 10:25
@fellz @ThomasPerche 

Could you please upload the `C:\Users\USER\AppData\Roaming\.particl\debug.log` on pastebin or https://transfer.sh/ ?
Either the daemon isn't starting or the RPC is timing out.

We've already updated the timeout to 30 seconds, might be a timing issue.
I will improve the error handling code there, it dialog you're seeing is an error we've created but isn't properly handled.

**Comment by fellz** [comment] 2018-01-28 12:07
the log is huge actually and i can expose some sensitive info i guess, so can i pass it to you by email @kewde

**Comment by kewde** [comment] 2018-01-28 13:40
@fellz

Ofcourse, kewde@particl.io

**Comment by pciavald** [comment] 2018-01-28 16:24
This is particl-desktop 1.1.0 with particld 0.15.0.4.0
This bug has probably already been fixed on the current dev branch.

**Comment by ThomasPerche** [comment] 2018-01-29 10:03
Hello,

It seems that the bug is resolved. Actually I succeed to launch the wallet. And I have succeed to connect too.

Thanks for the fix, the timeout increase seems to work perfectly

**Closed** 2018-02-02 15:23 UTC
Labels: bug
