### ISSUE TITLE
Total costs in cart not adding properly

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#987] opened 2018-05-10 22:17 UTC
# Math
On some orders in "Bidding" phase (waiting for seller) my items aren't adding properly. See:
![image](https://user-images.githubusercontent.com/6236019/39896934-388e9bea-547e-11e8-914d-f0dff66d5cd2.png)

Top item should be 0.004 PART

# Place a bid on multiple items

# More information

- Operating system and version: Windows 10
- Client version: 1.1.0-RC1-alpha

**Comment by HenkSwardt** [comment] 2018-05-11 05:37
Hi @LiteBit 

We have an issue locked for this that @vikas-cis is currently looking into. The inconsistancy is caused by the calculation of the shipping between domestic and international. If you continue with the checkout process you will see that the international shipping gets used by default. We are making a change to check if the shipping country and listing country matches. This will then use domestic shipping cost. If not International will be used to calculate the total.

Please see https://github.com/particl/particl-desktop/issues/985

**Comment by HenkSwardt** [comment] 2018-05-11 05:38
Closing as a duplicate

**Closed by HenkSwardt** 2018-05-11 05:38 UTC
Labels: duplicate

**Comment by LiteBit** [comment] 2018-05-11 15:25
thanks, sorry about the duplicate
