### ISSUE TITLE
can't unlock when using updated particl-desktop

### ISSUE THREAD

**Issue by elad-shtilerman** [particl/particl-desktop#853] opened 2018-02-18 19:24 UTC
# bug
after installing new particl-desktop 1.1.0 on ubuntu 16.04 in parallel to existing particl-wallet installation I can't unlock the wallet in the particl-desktop app. I can see the correct balance in the desktop however the password fails to unlock. The password works for the previous installation of the particl-wallet.

**Comment by pciavald** [comment] 2018-02-19 13:03
Hi @elad-shtilerman, thank you for the report.
Do you have the previous wallet or deamon running when you start your new wallet ?
what is the output of `ps aux | grep particld` ?

**Comment by momentmaker** [comment] 2018-02-19 23:18
I'm having the same issue. I'm using mac 10.13 sierra.

**Comment by kewde** [comment] 2018-02-20 01:23
Thank you for your bug report.

We might need a bit more information to debug the issue.
Please check that you can unlock the wallet with the latest Qt GUI first.

Does this issue persist or is it happening sporadically?
If there are any steps to reproduce this issue then please let us know.

Also starting the application with the `-devtools` will give you additional logging (see the console tab), let us know if there is anything out the ordinary when you unlock your wallet.

**Comment by momentmaker** [comment] 2018-02-20 01:33
It works fine with particl wallet, just the particl desktop not working. It's a persistent issue. Never worked for me.

**Comment by rynomster** [comment] 2018-02-20 03:07
Do you have a space at the end of your password?

**Comment by momentmaker** [comment] 2018-02-20 04:10
Nope.

**Comment by elad-shtilerman** [comment] 2018-02-22 21:36
For me somehow it works fine now. I don't why it didn't let me access in the beginning, perhaps it was syncing or something like that.

**Comment by momentmaker** [comment] 2018-03-05 00:54
It works for me now for some reason.

**Comment by AllienWorks** [comment] 2018-03-12 16:11
Since it's working for all of you, I'm closing the issue now. If you encounter this again, feel free to reopen it in the future.

**Closed by AllienWorks** 2018-03-12 16:11 UTC
Labels: PRG, bug, reporter feedback needed
