### ISSUE TITLE
Filter on the Sell->Listings page is not working properly

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1812] opened 2021-09-09 20:47 UTC
**Describe the bug**
In the Sell->Listings the Filter is not functioning properly. Selecting "Active" still shows all the listings, both expired and active. Selecting Expired shows nothing despite of having expired listings.

**To Reproduce**
1. Go to Sell->Listings
2. Select the "Active" or "Expired" options
3. Observe that in both options the listings are not properly filtered 

**Expected behavior**
Filter should be filtering correctly

**Versions (please complete the following information):**
 - OS: Linux Debian 10
 - Particl Desktop: testnet v3.0.0 RC005 on the testner
 - Particl Core: v0.19.2.13

**Comment by zaSmilingIdiot** [comment] 2021-09-10 08:38
Likely due to some regression, but this was previously fixed. Either way, this is a duplicate of #1799 so I'll close this in favour of tracking the progress further in that issue.

**Closed as completed** 2021-09-10 08:38 UTC
Labels: Resolve: Duplicate
