### ISSUE TITLE
Uploading a PNG image without background color information results in a black image in the listings view

### ISSUE THREAD

**Issue by btmr** [particl/particl-desktop#1623] opened 2019-08-01 20:55 UTC
# Describe bug/issue

Uploading a PNG image without background color information results in a fully black image in the listings view.

If this is unavoidable or desired behavior, the user needs to be informed during this step.

# How to reproduce

1. Create an image without background color information and save it as PNG.
2. Upload it in the Desktop using either drag&drop or file selection.

# More information

- Operating system and version: Linux Ubuntu 16.04
- Client version: 2.0.0-alpha2-testnet
- Market 0.0.78
- Core 0.18.1.0

I already submitted this bug for alpha1.

**Comment by zaSmilingIdiot** [comment] 2019-08-02 06:43
Closing this as a duplicate of https://github.com/particl/particl-desktop/issues/1613

**Closed as completed by zaSmilingIdiot** 2019-08-02 06:43 UTC
