### ISSUE TITLE
Wallet creation fails with mnemonic-related errors

### ISSUE THREAD

**Issue by Diti** [particl/particl-desktop#318] opened 2017-11-10 14:40 UTC
Seen on a classmate’s MacBook Pro:

1. Create a new wallet and save its seed;
2. On next step (verification), input seed words correctly (AFAIK—I double-checked);
3. Click next (several times, several error messages).

The error messages are:
* `MnemonicDecode failed: No. of words must be divisible by 3.`
* `MnemonicDecode failed: Checksum mismatch.`
* `ExtKeyImportLoose failed, Derived key already exists in wallet` (this one is rarer; about 1 time out of 10 clicks on Next)

![MnemonicDecode failed](https://user-images.githubusercontent.com/243344/32662161-d5fdd8ac-c629-11e7-95eb-53c86e3a7e76.png)

**Comment by Diti** [comment] 2017-11-10 15:04
I haven’t read the code, but the nature of the first two errors (the `MnemonicDecode` ones) makes me believe that this screen concatenates each field to get the final passphrase, and seems in this case to only concatenate the *values* of the fields, and **not** the *placeholders* (the pre-filled values in the screenshot above).

**Comment by kewde** [comment] 2017-11-10 17:03
> ExtKeyImportLoose failed, Derived key already exists in wallet
Means it actually went through eventually, which is quite odd.

I'll test this again, but I've been creating new wallets the past few days and I didn't get these errors, so there is some inconsistency there

**Comment by HenkSwardt** [comment] 2017-11-14 09:12
@vikas-cis will be investigating this issue.

**Comment by vikas-cis** [comment] 2017-11-14 13:38
I have check the issue but couldn't able to reproduce it on mac as well as on windows.

Thanks

**Comment by HenkSwardt** [comment] 2017-11-15 13:36
@Diti, Can I ask that you please enable debug logging and try to recreate this scenario for us. If you manage to get the same behavior please supply us with the log file on this issue. 

Thank you

**Comment by pciavald** [comment] 2018-01-18 18:10
fixed

**Closed by pciavald** 2018-01-18 18:10 UTC
Labels: bug, needs-testing, reporter feedback needed

**Comment by bracklanna** [comment] 2019-01-19 01:53
Hi I'm commenting here as I am experiencing a similar error with the latest version of Particl Desktop for Mac, version 1.3.0, daemon version 0.17.0.1.

I am attempting to restore a previously-created wallet (created in Nov. 2017, for which I backed up the mnemonic at that time) to a brand-new install of the current Particl Mac desktop client.

Here is the sequence of events:

- I tried out Particl back in November 2017 & created a wallet. At that time the recovery phrase I was given (when I created the wallet) was 48 words long. I copy-pasted that recovery phrase into safe storage.

- In the intervening period I got a new computer, completely wiped my HD and all previous traces of Particle, reinstalled the most recent version of OS X, etc. (Starting from scratch.)

- Today I downloaded the latest Particl Desktop client for Mac and attempted to restore my wallet using the 48-word recovery phrase I had previously stored.

When attempting to do so I get the error, "MnemonicDecode failed: checksum mismatch"

I am quite sure that I have the correct mnemonic because when I created & stored it I used copy-paste to move it to my safe storage. I did not try to copy it by hand.

Please advise on what I should try doing in order to restore from this 48-word seed and then convert my wallet format to one that is compatible with the current Particl Desktop for Mac client.

Thanks.

**Comment by rynomster** [comment] 2019-01-19 06:42
Hi bracklanna, the default key generation size is 24 words. Could you try restore the first 24 words and the last 24 words and see if any of those combinations work?

**Comment by bracklanna** [comment] 2019-01-19 06:49
Hi rynomster,

I just tried that (after deleting Wallet.dat and restarting particl-desktop). Same result, "Checksum mismatch."

I have double-checked that I am not pasting in any strange or extra characters. I copied the text into TextEdit and then did "make plain text" before re-copying and then pasting it into Particl.

Was there some point in time when Particl did issue 48-word seeds by default? Or did I make some mistake back in Nov 2017 during initial wallet generation?

**Comment by rynomster** [comment] 2019-01-19 06:53
We've only had 24 words on Particl desktop. It's possible you had 24 words as the recovery mnemonic and 24 words as the recovery phrase

**Comment by bracklanna** [comment] 2019-01-19 06:57
Hmm. I tried all the combinations of first 24-words / last 24-words in the seed phrase / recovery phrase fields but am not able to make any progress.  

(First part / Second part
First part / blank
Second part / First Part
Second part / blank)

The wallet is not high-value but may contain some nominal amount of tokens. Would you mind if I PM'ed the 48 words to you & ask you to try recovering it?

**Comment by zaSmilingIdiot** [comment] 2019-01-19 07:47
A bit of a long shot but are any of the words duplicates?

**Comment by rynomster** [comment] 2019-01-19 07:50
I'm currently in the Netherlands, flying home today. Do you have riot or telegram? You Can message me on the same handle
