### ISSUE TITLE
Cant rebuy a item after vendor rejected it

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#1547] opened 2019-04-02 12:33 UTC
Describe the steps needed to recreate the bug/issue:

1. .. buy a item
2. .. let the vendor reject it

Bid on an item and let the vendor reject the bid ... new bid on this item is not possible. Button for bidding on item is vanished.

# More information

- Operating system and version: linux
- Client version: latest

**Comment by zaSmilingIdiot** [comment] 2019-04-02 12:40
Hi @SativaL . This is the same issue as https://github.com/particl/particl-desktop/issues/1421 . Currently only bidding on a single item once is allowed, but bids for multiple items (across multiple purchases) is being worked on and should be a part of a future release.

**Comment by SativaL** [comment] 2019-04-03 12:39
"and should be a part of a future release." next testnet version or what future release do you mean ?

It will be implemented before mainnet right ?

**Comment by zaSmilingIdiot** [comment] 2019-04-11 14:58
I don't believe this will realistically be included in the alpha mainnet release. This first mainnet release is intended as an alpha release, with the intention that additional features will be included as they are completed.

The ability to place a bid on multiple of the same items has the implicit idea that the seller is able to indicate that multiple items are available. This also leads to additional requirements: if 2 bids arrive and the seller has enough to satisfy each individually, but not both together, how do they indicate to at least one bidder/buyer that there are not enough items to match the request quantity? In which case, what if that buyer wanted that exact amount or else doesn't want the bid to proceed. What if they don't mind a lesser quantity. And this is assuming that the buyer for whom the bid was accepted actually proceeds to escrow.

So the above is a couple of simple scenario examples, but all need to be properly catered for when considering the feature. So it is currently slated for one of the beta releases, but will likely not be in the alpha release.

**Comment by zaSmilingIdiot** [comment] 2019-08-28 10:18
The desktop currently allows a buyer to create a single bid on an item. A seller, however, can accept multiple bids from any number of people, as they so choose. Acceptance of a bid (by a seller) does not automatically update other bids. It is the seller's discretion to accept or reject bids on a single listing according to the stock quantity and/or based on other self-chosen requirements.

This is currently by design. A future feature should allow for multiple bids on a single listing item by a single buyer. But this is not built into the desktop currently.

Closing this as a duplicate request of https://github.com/particl/particl-desktop/issues/1421

**Closed as completed by zaSmilingIdiot** 2019-08-28 10:18 UTC
